# syntax=docker/dockerfile:1
FROM python:3.10

WORKDIR /app
COPY . .

RUN pip install cpl-cli --extra-index-url https://pip.sh-edraft.de
RUN pip install cpl-discord --extra-index-url https://pip.sh-edraft.de
RUN pip install cpl-query --extra-index-url https://pip.sh-edraft.de
RUN pip install cpl-translation --extra-index-url https://pip.sh-edraft.de

ENV DISCORD_TOKEN=""
ENV DISCORD_PREFIX=""

CMD [ "cpl", "run"]
